# Generated by Django 4.0.4 on 2022-05-01 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters_app', '0002_player'),
        ('users', '0002_player_playerchoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerchoices',
            name='player_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_1', to='masters_app.player'),
        ),
        migrations.AlterField(
            model_name='playerchoices',
            name='player_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_2', to='masters_app.player'),
        ),
        migrations.AlterField(
            model_name='playerchoices',
            name='player_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_3', to='masters_app.player'),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
