version: "3.9"

services:
  web:
    build: .
    environment:
      POSTGRES_DB_PORT : $DB_PORT
      POSTGRES_DB_HOST : $DB_HOST
      POSTGRES_DB_USER : $DB_USER
      POSTGRES_DB_PASSWORD : $DB_PASSWORD
      POSTGRES_DB_NAME : $DB_NAME
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
