# Generated by Django 4.0.4 on 2022-05-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters_app', '0003_playerchoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerchoices',
            name='predicted_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
