# Generated by Django 4.0.4 on 2022-05-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters_app', '0004_playerchoices_predicted_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerchoices',
            name='predicted_score',
            field=models.IntegerField(null=True),
        ),
    ]
